In [6]:
import torch
import torch.nn as nn

In [7]:
inputs = torch.tensor([1.0, 2.0, 3.0])
neuron = nn.Linear(in_features = 3, out_features = 1)

In [11]:
output = neuron(inputs)
output

tensor([-2.1116], grad_fn=<ViewBackward0>)

In [12]:
neuron.bias

Parameter containing:
tensor([0.2375], requires_grad=True)

In [13]:
neuron.weight @ inputs + neuron.bias

tensor([-2.1116], grad_fn=<AddBackward0>)